/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author LaptopSA
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        idFactura = new javax.swing.JLabel();
        idClienteFactura = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        rucFactura = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        rucFactura1 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        rucFactura2 = new javax.swing.JLabel();
        rucFactura3 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        btnCerrarFactura = new javax.swing.JButton();
        titulo5 = new javax.swing.JLabel();
        rucFactura4 = new javax.swing.JLabel();
        titulo6 = new javax.swing.JLabel();
        rucFactura5 = new javax.swing.JLabel();
        rucFactura6 = new javax.swing.JLabel();
        titulo7 = new javax.swing.JLabel();
        btnCerrarFactura1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo.setText("FACTURA");

        id.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        id.setText("ID DEL CLIENTE");
        id.setEnabled(false);

        id1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        id1.setText("ID DE LA FACTURA");
        id1.setEnabled(false);

        idFactura.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        idFactura.setText("jLabel1");
        idFactura.setEnabled(false);

        idClienteFactura.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        idClienteFactura.setText("jLabel1");
        idClienteFactura.setEnabled(false);

        titulo1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo1.setText("RUC");

        rucFactura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        rucFactura.setText("xd");
        rucFactura.setEnabled(false);

        titulo2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo2.setText("DIRECCION");

        rucFactura1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        rucFactura1.setText("xd");
        rucFactura1.setEnabled(false);

        titulo3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo3.setText("TELEFONO");

        rucFactura2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        rucFactura2.setText("xd");
        rucFactura2.setEnabled(false);

        rucFactura3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        rucFactura3.setText("xd");
        rucFactura3.setEnabled(false);

        titulo4.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo4.setText("FECHA");

        btnCerrarFactura.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCerrarFactura.setText("IMPRIMIR FACTURA");

        titulo5.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo5.setText("SUBTOTAL");

        rucFactura4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        rucFactura4.setText("xd");
        rucFactura4.setEnabled(false);

        titulo6.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo6.setText("IVA");

        rucFactura5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        rucFactura5.setText("xd");
        rucFactura5.setEnabled(false);

        rucFactura6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        rucFactura6.setText("xd");
        rucFactura6.setEnabled(false);

        titulo7.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo7.setText("TOTAL");

        btnCerrarFactura1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCerrarFactura1.setText("AGREGAR ITEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rucFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idClienteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(id1)
                                        .addGap(67, 67, 67)
                                        .addComponent(btnCerrarFactura1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rucFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rucFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rucFactura2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(titulo)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(titulo5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rucFactura4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rucFactura6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(titulo6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rucFactura5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCerrarFactura)
                        .addGap(184, 184, 184)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idClienteFactura))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id1)
                            .addComponent(btnCerrarFactura1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idFactura)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rucFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rucFactura1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rucFactura2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rucFactura3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rucFactura4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rucFactura5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rucFactura6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo7))
                .addGap(18, 18, 18)
                .addComponent(btnCerrarFactura)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCerrarFactura() {
        return btnCerrarFactura;
    }

    public void setBtnCerrarFactura(JButton btnCerrarFactura) {
        this.btnCerrarFactura = btnCerrarFactura;
    }

    public JLabel getId() {
        return id;
    }

    public void setId(JLabel id) {
        this.id = id;
    }

    public JLabel getId1() {
        return id1;
    }

    public void setId1(JLabel id1) {
        this.id1 = id1;
    }

    public JLabel getIdClienteFactura() {
        return idClienteFactura;
    }

    public void setIdClienteFactura(JLabel idClienteFactura) {
        this.idClienteFactura = idClienteFactura;
    }

    public JLabel getIdFactura() {
        return idFactura;
    }

    public void setIdFactura(JLabel idFactura) {
        this.idFactura = idFactura;
    }

    public JLabel getRucFactura() {
        return rucFactura;
    }

    public void setRucFactura(JLabel rucFactura) {
        this.rucFactura = rucFactura;
    }

    public JLabel getRucFactura1() {
        return rucFactura1;
    }

    public void setRucFactura1(JLabel rucFactura1) {
        this.rucFactura1 = rucFactura1;
    }

    public JLabel getRucFactura2() {
        return rucFactura2;
    }

    public void setRucFactura2(JLabel rucFactura2) {
        this.rucFactura2 = rucFactura2;
    }

    public JLabel getRucFactura3() {
        return rucFactura3;
    }

    public void setRucFactura3(JLabel rucFactura3) {
        this.rucFactura3 = rucFactura3;
    }

    public JLabel getRucFactura4() {
        return rucFactura4;
    }

    public void setRucFactura4(JLabel rucFactura4) {
        this.rucFactura4 = rucFactura4;
    }

    public JLabel getRucFactura5() {
        return rucFactura5;
    }

    public void setRucFactura5(JLabel rucFactura5) {
        this.rucFactura5 = rucFactura5;
    }

    public JLabel getRucFactura6() {
        return rucFactura6;
    }

    public void setRucFactura6(JLabel rucFactura6) {
        this.rucFactura6 = rucFactura6;
    }

    public JLabel getTitulo() {
        return titulo;
    }

    public void setTitulo(JLabel titulo) {
        this.titulo = titulo;
    }

    public JLabel getTitulo1() {
        return titulo1;
    }

    public void setTitulo1(JLabel titulo1) {
        this.titulo1 = titulo1;
    }

    public JLabel getTitulo2() {
        return titulo2;
    }

    public void setTitulo2(JLabel titulo2) {
        this.titulo2 = titulo2;
    }

    public JLabel getTitulo3() {
        return titulo3;
    }

    public void setTitulo3(JLabel titulo3) {
        this.titulo3 = titulo3;
    }

    public JLabel getTitulo4() {
        return titulo4;
    }

    public void setTitulo4(JLabel titulo4) {
        this.titulo4 = titulo4;
    }

    public JLabel getTitulo5() {
        return titulo5;
    }

    public void setTitulo5(JLabel titulo5) {
        this.titulo5 = titulo5;
    }

    public JLabel getTitulo6() {
        return titulo6;
    }

    public void setTitulo6(JLabel titulo6) {
        this.titulo6 = titulo6;
    }

    public JLabel getTitulo7() {
        return titulo7;
    }

    public void setTitulo7(JLabel titulo7) {
        this.titulo7 = titulo7;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarFactura;
    private javax.swing.JButton btnCerrarFactura1;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel idClienteFactura;
    private javax.swing.JLabel idFactura;
    private javax.swing.JLabel rucFactura;
    private javax.swing.JLabel rucFactura1;
    private javax.swing.JLabel rucFactura2;
    private javax.swing.JLabel rucFactura3;
    private javax.swing.JLabel rucFactura4;
    private javax.swing.JLabel rucFactura5;
    private javax.swing.JLabel rucFactura6;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    private javax.swing.JLabel titulo5;
    private javax.swing.JLabel titulo6;
    private javax.swing.JLabel titulo7;
    // End of variables declaration//GEN-END:variables
}
