/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author LaptopSA
 */
public class FacturaV extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public FacturaV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        idFactura = new javax.swing.JLabel();
        cedulaCliente = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        rucFactura = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        rucFactura1 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        telefonoFactura = new javax.swing.JLabel();
        fechaFactura = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        btnCerrarFactura = new javax.swing.JButton();
        titulo5 = new javax.swing.JLabel();
        subtotalFactura = new javax.swing.JLabel();
        titulo6 = new javax.swing.JLabel();
        ivaFactura = new javax.swing.JLabel();
        totalFactura = new javax.swing.JLabel();
        titulo7 = new javax.swing.JLabel();
        btnAgregarItem = new javax.swing.JButton();
        direccionFactura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titulo.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo.setText("FACTURA");

        id.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        id.setText("CÉDULA DEL CLIENTE");
        id.setEnabled(false);

        id1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        id1.setText("ID DE LA FACTURA");
        id1.setEnabled(false);

        idFactura.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        idFactura.setText("jLabel1");
        idFactura.setEnabled(false);

        cedulaCliente.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        cedulaCliente.setText("jLabel1");
        cedulaCliente.setEnabled(false);

        titulo1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo1.setText("RUC");

        rucFactura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        rucFactura.setEnabled(false);

        titulo2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo2.setText("DIRECCIÓN");

        rucFactura1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        rucFactura1.setEnabled(false);

        titulo3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo3.setText("TELÉFONO");

        telefonoFactura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        telefonoFactura.setEnabled(false);

        fechaFactura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        fechaFactura.setEnabled(false);

        titulo4.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo4.setText("FECHA");

        btnCerrarFactura.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCerrarFactura.setText("FINALIZAR FACTURA");

        titulo5.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo5.setText("SUBTOTAL");

        subtotalFactura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        subtotalFactura.setEnabled(false);

        titulo6.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo6.setText("IVA");

        ivaFactura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ivaFactura.setEnabled(false);

        totalFactura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        totalFactura.setEnabled(false);

        titulo7.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        titulo7.setText("TOTAL");

        btnAgregarItem.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnAgregarItem.setText("AGREGAR ÍTEM");
        btnAgregarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarItemActionPerformed(evt);
            }
        });

        direccionFactura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        direccionFactura.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(id1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAgregarItem))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(titulo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rucFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(titulo2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(titulo3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(telefonoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(titulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnCerrarFactura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rucFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(direccionFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 245, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(subtotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(titulo7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(totalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(titulo6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ivaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id1)
                    .addComponent(btnAgregarItem)
                    .addComponent(id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idFactura)
                    .addComponent(cedulaCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rucFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rucFactura1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo2)
                    .addComponent(direccionFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telefonoFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fechaFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subtotalFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo6)
                    .addComponent(ivaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo7))
                .addGap(18, 18, 18)
                .addComponent(btnCerrarFactura)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarItemActionPerformed

    public JButton getBtnAgregarItem() {
        return btnAgregarItem;
    }

    public void setBtnAgregarItem(JButton btnAgregarItem) {
        this.btnAgregarItem = btnAgregarItem;
    }

    public JButton getBtnCerrarFactura() {
        return btnCerrarFactura;
    }

    public void setBtnCerrarFactura(JButton btnCerrarFactura) {
        this.btnCerrarFactura = btnCerrarFactura;
    }

    public JLabel getCedulaCliente() {
        return cedulaCliente;
    }

    public void setCedulaCliente(JLabel cedulaCliente) {
        this.cedulaCliente = cedulaCliente;
    }

    public JLabel getDireccionFactura() {
        return direccionFactura;
    }

    public void setDireccionFactura(JLabel direccionFactura) {
        this.direccionFactura = direccionFactura;
    }

    public JLabel getFechaFactura() {
        return fechaFactura;
    }

    public void setFechaFactura(JLabel fechaFactura) {
        this.fechaFactura = fechaFactura;
    }

    public JLabel getId() {
        return id;
    }

    public void setId(JLabel id) {
        this.id = id;
    }

    public JLabel getId1() {
        return id1;
    }

    public void setId1(JLabel id1) {
        this.id1 = id1;
    }

    public JLabel getIdFactura() {
        return idFactura;
    }

    public void setIdFactura(JLabel idFactura) {
        this.idFactura = idFactura;
    }

    public JLabel getIvaFactura() {
        return ivaFactura;
    }

    public void setIvaFactura(JLabel ivaFactura) {
        this.ivaFactura = ivaFactura;
    }

    public JLabel getRucFactura() {
        return rucFactura;
    }

    public void setRucFactura(JLabel rucFactura) {
        this.rucFactura = rucFactura;
    }

    public JLabel getRucFactura1() {
        return rucFactura1;
    }

    public void setRucFactura1(JLabel rucFactura1) {
        this.rucFactura1 = rucFactura1;
    }

    public JLabel getSubtotalFactura() {
        return subtotalFactura;
    }

    public void setSubtotalFactura(JLabel subtotalFactura) {
        this.subtotalFactura = subtotalFactura;
    }

    public JLabel getTelefonoFactura() {
        return telefonoFactura;
    }

    public void setTelefonoFactura(JLabel telefonoFactura) {
        this.telefonoFactura = telefonoFactura;
    }

    public JLabel getTitulo() {
        return titulo;
    }

    public void setTitulo(JLabel titulo) {
        this.titulo = titulo;
    }

    public JLabel getTitulo1() {
        return titulo1;
    }

    public void setTitulo1(JLabel titulo1) {
        this.titulo1 = titulo1;
    }

    public JLabel getTitulo2() {
        return titulo2;
    }

    public void setTitulo2(JLabel titulo2) {
        this.titulo2 = titulo2;
    }

    public JLabel getTitulo3() {
        return titulo3;
    }

    public void setTitulo3(JLabel titulo3) {
        this.titulo3 = titulo3;
    }

    public JLabel getTitulo4() {
        return titulo4;
    }

    public void setTitulo4(JLabel titulo4) {
        this.titulo4 = titulo4;
    }

    public JLabel getTitulo5() {
        return titulo5;
    }

    public void setTitulo5(JLabel titulo5) {
        this.titulo5 = titulo5;
    }

    public JLabel getTitulo6() {
        return titulo6;
    }

    public void setTitulo6(JLabel titulo6) {
        this.titulo6 = titulo6;
    }

    public JLabel getTitulo7() {
        return titulo7;
    }

    public void setTitulo7(JLabel titulo7) {
        this.titulo7 = titulo7;
    }

    public JLabel getTotalFactura() {
        return totalFactura;
    }

    public void setTotalFactura(JLabel totalFactura) {
        this.totalFactura = totalFactura;
    }
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarItem;
    private javax.swing.JButton btnCerrarFactura;
    private javax.swing.JLabel cedulaCliente;
    private javax.swing.JLabel direccionFactura;
    private javax.swing.JLabel fechaFactura;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel idFactura;
    private javax.swing.JLabel ivaFactura;
    private javax.swing.JLabel rucFactura;
    private javax.swing.JLabel rucFactura1;
    private javax.swing.JLabel subtotalFactura;
    private javax.swing.JLabel telefonoFactura;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    private javax.swing.JLabel titulo5;
    private javax.swing.JLabel titulo6;
    private javax.swing.JLabel titulo7;
    private javax.swing.JLabel totalFactura;
    // End of variables declaration//GEN-END:variables
}
